version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    image: "omero-server:custom"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"

  omeroweb:
    image: "openmicroscopy/omero-web-standalone:5.6"
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"
    volumes:
      - "./web-config.omero:/opt/omero/web/config/web-config.omero:ro"

networks:
  omero:

volumes:
  database:
       driver_opts:
           type: none
           device: ${DB_VOLUME} 
           o: bind
  omero:
       driver_opts:
           type: none
           device: ${OMERO_VOLUME}
           o: bind
